name: Golang App Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Install nodejs and golang
        run: sudo apk add --update go nodejs npm

      - name: Install depenendencies
        run: go mod tidy

      - name: Build Application
        run: go build -o main

      - name: Install pm2
        run: sudo npm install pm2@latest -g

  deploy:
    steps:
      - name: Start App with pm2
        run: pm2 delete "golang-app" || true && pm2 start "./main" --name "golang-app"

      - name: Save pm2 config
        run: pm2 save
